"""Shared constants for the rewritten TikTok collector."""

DEFAULT_RENDER_WAIT_SECONDS = 30
MIN_RENDER_WAIT_SECONDS = 5
DEFAULT_PROXY_PORT_START = 7901

TASK_MODE_RECOMMEND = "recommend"
TASK_MODE_HASHTAG = "hashtag"

ENV_STATUS_NEW = "NEW"
ENV_STATUS_READY = "READY"
ENV_STATUS_LOGIN_REQUIRED = "LOGIN_REQUIRED"
ENV_STATUS_RUNNING = "RUNNING"
ENV_STATUS_ERROR = "ERROR"

